#!/bin/bash
rm count_files.txt
rm data.txt
python countPatchDockPoses.py 3F74_A_B
python countPatchDockPoses.py 3HRD_E_H
python countPatchDockPoses.py 1ERN_A_B
python countPatchDockPoses.py 2B3Z_C_D
python countPatchDockPoses.py 4KGG_C_A
python countPatchDockPoses.py 2FE8_A_C
python countPatchDockPoses.py 1SOT_A_C
python countPatchDockPoses.py 2LBU_E_D
python countPatchDockPoses.py 3PGA_1_4
python countPatchDockPoses.py 3QWN_I_J
python countPatchDockPoses.py 3TND_B_D
python countPatchDockPoses.py 1XDT_T_R
python countPatchDockPoses.py 3OGF_A_B
python countPatchDockPoses.py 1YLQ_A_B
python countPatchDockPoses.py 2GD4_C_B
python countPatchDockPoses.py 2O8Q_A_B
python countPatchDockPoses.py 4CJ0_A_B
python countPatchDockPoses.py 3HN6_B_D
python countPatchDockPoses.py 1JZO_A_B
python countPatchDockPoses.py 1A2K_C_AB
python countPatchDockPoses.py 3BTV_A_B
python countPatchDockPoses.py 3E2U_A_E
python countPatchDockPoses.py 2J12_A_B
python countPatchDockPoses.py 1O9Y_A_D
python countPatchDockPoses.py 1YY9_A_D
python countPatchDockPoses.py 3SGB_E_I
python countPatchDockPoses.py 3AXY_B_D
python countPatchDockPoses.py 1AVX_A_B
python countPatchDockPoses.py 1I4O_B_D
python countPatchDockPoses.py 3ECY_A_B
python countPatchDockPoses.py 2P45_A_B
python countPatchDockPoses.py 1Z0K_A_C
python countPatchDockPoses.py 3WN7_A_B
python countPatchDockPoses.py 3CDW_A_H
python countPatchDockPoses.py 2WQ4_A_C
python countPatchDockPoses.py 3P71_C_T
python countPatchDockPoses.py 3EYD_C_D
python countPatchDockPoses.py 2YZJ_A_C
python countPatchDockPoses.py 1T0F_A_B
python countPatchDockPoses.py 3M85_B_E
python countPatchDockPoses.py 2JI1_C_D
python countPatchDockPoses.py 1XPJ_A_D
python countPatchDockPoses.py 2QLC_C_B
python countPatchDockPoses.py 3HCG_A_C
python countPatchDockPoses.py 2Y32_B_D
python countPatchDockPoses.py 3P8B_C_D
python countPatchDockPoses.py 5GPG_A_B
python countPatchDockPoses.py 1ID5_H_L
python countPatchDockPoses.py 1I07_A_B
python countPatchDockPoses.py 4TQ1_A_B
python countPatchDockPoses.py 3K3C_A_B
python countPatchDockPoses.py 1XT9_A_B
python countPatchDockPoses.py 1ZR0_A_B
python countPatchDockPoses.py 2P47_A_B
python countPatchDockPoses.py 4YDJ_HL_G
python countPatchDockPoses.py 3Q9U_A_C
python countPatchDockPoses.py 3KZH_A_B
python countPatchDockPoses.py 2HDP_A_B
python countPatchDockPoses.py 1UGH_E_I
python countPatchDockPoses.py 3CG8_C_B
python countPatchDockPoses.py 3FJS_C_D
python countPatchDockPoses.py 3SLH_A_B
python countPatchDockPoses.py 3B5U_J_L
python countPatchDockPoses.py 1Q5H_A_B
python countPatchDockPoses.py 1SHY_A_B
python countPatchDockPoses.py 2Z29_A_B
python countPatchDockPoses.py 1LQM_E_F
python countPatchDockPoses.py 1JKG_A_B
python countPatchDockPoses.py 4AG2_A_C
python countPatchDockPoses.py 3QWQ_A_B
python countPatchDockPoses.py 1BRS_A_D
python countPatchDockPoses.py 2GKW_A_B
python countPatchDockPoses.py 2Z0P_C_D
python countPatchDockPoses.py 3IBM_A_B
python countPatchDockPoses.py 3CHW_A_P
python countPatchDockPoses.py 2G2W_A_B
python countPatchDockPoses.py 1TQ9_A_B
python countPatchDockPoses.py 1NPO_A_C
python countPatchDockPoses.py 2AQX_A_B
python countPatchDockPoses.py 3KMT_A_B
python countPatchDockPoses.py 2ZXW_O_U
python countPatchDockPoses.py 2WAM_A_C
python countPatchDockPoses.py 3Q87_A_B
python countPatchDockPoses.py 2I32_A_E
python countPatchDockPoses.py 2B42_B_A
python countPatchDockPoses.py 1PXV_A_C
python countPatchDockPoses.py 4M5F_A_B
python countPatchDockPoses.py 3RDZ_A_C
python countPatchDockPoses.py 1XUA_A_B
python countPatchDockPoses.py 1UUG_A_B
python countPatchDockPoses.py 3S8V_A_X
python countPatchDockPoses.py 1ZVN_A_B
python countPatchDockPoses.py 2A2L_C_B
python countPatchDockPoses.py 2Z7F_E_I
python countPatchDockPoses.py 3Q0Y_C_B
python countPatchDockPoses.py 3S9C_A_B
python countPatchDockPoses.py 1HBT_I_H
python countPatchDockPoses.py 3ISM_A_B
python countPatchDockPoses.py 3CEW_C_D
python countPatchDockPoses.py 2HEK_A_B
